# Generated by Django 2.2.28 on 2023-08-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodelinfoo',
            name='field_two',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
