# Generated by Django 2.2.28 on 2023-08-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test_02'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_02',
        ),
    ]
